Binge-buddy-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "welcome#home", as: "home_page"


  resources :users
  # get "/movies/guideboxwrapper"  => "movies#guideboxwrapper"


  get "/movies/search" => "movies#search_form", as: "movie_search"

  post "/movies/search-results"       => "movies#search_results"
  get "/movies/search-results"       => "movies#search_results"
  post "/movies/one_result"      => "movies#one_result"

  get "/movies/one_result"      => "movies#one_result", as: "one_result"

  resources :movies






end

Binge-buddy-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Binge-buddy-app/app/models/movie.rb
class Movie < ApplicationRecord

 belongs_to :user
 # serialize(:purchase_web_sources, Array)

end

Binge-buddy-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :movies
  # devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
# paperclip
 has_attached_file :avatar,
                :styles => { :medium => "300x300px>", :thumb => "100x100px>" },
                :default_url => "/assets/default-user-image.png"
 
         validates_attachment_content_type :avatar,
                :content_type => /\Aimage\/.*\Z/


end

Binge-buddy-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected
  #  need to add name and address key in order to render in browser
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :first_name, :last_name,])
     devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :first_name, :last_name])
   end
  def  after_sign_in_path_for(resource)
    user_path(resource.id)
  end



end

Binge-buddy-app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
require 'uri'
# serialize(:free_web_sources, Array)
    def index
      @movies = Movie.all
      @user = User.find(current_user.id)
      @saved = @user.movies
    end

    def search_results

      #search params
        @searching = params[:search]
      if current_user != nil
      #this is to get limit of 10 movies
        @guidebox = HTTParty.get("https://api-public.guidebox.com/v2/movies?api_key=#{ENV['GUIDEBOXWRAPPER_API_KEY']}&limit=10")
          if @searching != nil
              @search = URI.encode(@searching)
      #this is get the searched movie results
        @guidebox_movie = HTTParty.get("https://api-public.guidebox.com/v1.43/all/#{ENV['GUIDEBOXWRAPPER_API_KEY']}/search/movie/title/#{@search}/fuzzy/web")
        # render :json => @guidebox_movie
        @movieslist = @guidebox['results']
        @moviesearch = @guidebox_movie['results']
          else
             redirect_to url_for(:controller => :movies, :action => :search_results)
           end
      else
        @searching = params[:search]
        @search = URI.encode(@searching)
        @guidebox_movie = HTTParty.get("https://api-public.guidebox.com/v1.43/all/#{ENV['GUIDEBOXWRAPPER_API_KEY']}/search/movie/title/#{@search}/fuzzy/web")
        @moviesearch = @guidebox_movie['results']
      end
    end

    def one_result
      puts "CHECK ALLO ", params.inspect
      @movie_id = params[:movie_id]
      @trailer= HTTParty.get("https://api-public.guidebox.com/v2/movies/#{@movie_id}?api_key=#{ENV['GUIDEBOXWRAPPER_API_KEY']}")

      puts "https://api-public.guidebox.com/v2/movies/#{@movie_id}?api_key=#{ENV['GUIDEBOXWRAPPER_API_KEY']}"

      # render :json  => @trailer
      puts "TRAILER", @trailer
    end

    def create
      @new_movie = Movie.new(
         title: params[:title],
         genre: params[:genre].to_i,
         time: params[:duration],
         user_id: params[:user_id],
         writers: params[:writers],
         movie_id: params[:movie_id],
         release_year: params[:release_year],
         directors: params[:directors],
         rottentomatoes: params[:rottentomatoes],
         web_trailers: params[:web_trailers],
         posters: params[:posters],
         metacritic_link: params[:metacritic_link],
         free_web_sources: params[:free_web_sources],
         thumbnails: params[:thumbnails],
         banners: params[:banners],
         overview: params[:overview],
         purchase_web_sources: params[:purchase_web_sources],
         tv_everywhere_web_sources: params[:tv_everywhere_web_sources],
         search: params[:search]
          )
      @new_movie.save
      puts "New Movie", @new_movie.inspect
    end

    # def show
    # end

    def edit
    end

    def update

    end

    def destroy
      Movie.delete(params[:id])
      redirect_to url_for(:controller => :movies, :action => :index)
    end



end

Binge-buddy-app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

    def index
      @users = User.all
    end

    def new
    end
    def create
        puts "CHECK HERE", params.inspect
    end

    def show
      @user =User.find(params[:id])

    end

    def edit

    end

    def update

    end

    def destroy
    end



end

Binge-buddy-app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @message = "yo welcome to binging and budging!"
    @guidebox = HTTParty.get("https://api-public.guidebox.com/v2/movies?api_key=#{ENV['GUIDEBOXWRAPPER_API_KEY']}&limit=15")
    puts "CHECK", "https://api-public.guidebox.com/v2/movies?api_key=#{ENV['GUIDEBOXWRAPPER_API_KEY']}&limit=15"

  end

end

Binge-buddy-app/app/helpers/application_helper.rb
module ApplicationHelper
end

Binge-buddy-app/app/helpers/movies_helper.rb
module MoviesHelper
end

Binge-buddy-app/app/helpers/users_helper.rb
module UsersHelper
end

Binge-buddy-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Binge-buddy-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BingeBuddyApp</title>
    <%= csrf_meta_tags %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700|Raleway+Dots|Raleway:200,300,400" rel="stylesheet">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </head>

  <body>

    <div id="header-wrap"  class="nav">
      <div id="header1">


        <%= link_to image_tag("/assets/logo.jpeg"), home_page_path, id: "right"%>
       <!-- <img id= "right" src="/assets/logo.jpeg" alt=  ""> -->
      	<% if  (user_signed_in?) %>
          <div class="BG">
          <li><%= link_to '<i class="small material-icons">https</i>'.html_safe, { :action => "destroy", :controller=> "devise/sessions"}, method: :delete %></li>
          <li><%= link_to '<i class="small material-icons">favorite</i>'.html_safe, movies_path %></li>
          <li><%= link_to '<i class="small material-icons">search</i>'.html_safe, movie_search_path %></li>
          <li><%= link_to '<i class="small material-icons">perm_identity</i>'.html_safe, user_path(current_user.id) %></li>
          <li><%= link_to '<i class="small material-icons">home</i>'.html_safe, home_page_path %></li>
          </div>
        <% else %>
        	<li><%= link_to "Sign In", new_user_session_path %></li>
        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to '<i class="small material-icons">home</i>'.html_safe, home_page_path %></li>
      	<% end %>
      </div>
    </div>



       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="bodying ">

    <%= yield %>
  <!-- </div> -->
  <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
    <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script> -->
  </body>
</html>

Binge-buddy-app/app/views/movies/index.html.erb
<center><h4 id="allo">My Movies</h4>

<div class="container">
  <div class="row">
    <div class="col s12">
        <div class="honeycombs">
              <% @saved.each do |response| %>
              <%puts 'response', response.inspect%>
              <div class="col s12 m6 l4">
                <div class="comb">
                    <img src= <%= response.posters %> >
                    <span>
                    <%= response.title %><br>
                    <%= link_to "VIEW", {action: :one_result, movie_id: response.movie_id, title: response.title, user_id: current_user.id }, method: :post %> <br>
                    <%= link_to 'Delete',  { action: :destroy, id: response.id }, method: :delete%>
                  </span>
              <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.honeycombs').honeycombs({
      combWidth: 250,
      margin: 10
    });
  });
</script>

Binge-buddy-app/app/views/movies/one_result.html.erb
<%puts "RAILS CURRENT ENV"%>
<%puts Rails.env%>
<%@movie_id = @trailer['id']%>

<div class="mock-div5"></div>


<div id="above-the-fold" class="flex-container ">
  <div class="flex-item">
    <% @title = @trailer['title'] %>
    <p class="top"><%= @title %></p>
    <!-- <p class="bottom">A c t o r  /  A c t i v i s t</p> -->
  </div>

  <!-- video -->
  <video muted="" id="myvideo" loop="loop" autoplay="autoplay">
    <!-- Placeholder video to push to GH/Heroku -->
      <!-- <source src="http://www.starmenusa.com/clients/tony/video/tony.webm" type="video/webm"> -->

    <source src="/assets/BG-vid.mp4"type="video/mp4">

  </video>
</div> <!-- end above the fold -->








<div class="container">
  <div class="row">
    <div class="pade col s12">
      <div class="hexagon hexagon2">
        <div class="hexagon-in1">
            <%@image = @trailer['poster_240x342'].insert(4, 's')%>
            <img class= "hexagon-in5" src=<%= @image %> alt="">
        </div>
      </div>
    </div>
    <div class="col s12">
      <% if current_user != nil %>
             <center id ="heart"><%= link_to '<i class="large material-icons">favorite</i>'.html_safe, {action: :create, movie_id: @movie_id, title: @trailer['title'], user_id: current_user.id, posters: @image }, method: :post, remote: true, class: 'savebbttn' %> </center>
        <%else %>
          <!-- <i class="medium material-icons" href= "">favorite</i> -->
          <center id ="heart"><%= link_to '<i class="large material-icons">favorite</i>'.html_safe, new_user_registration_path, class: 'sign' %> </center>

          <!-- <center><a class="sign"href="/users/sign_up"> Sign Up</a> </center> -->
        <%end %>
    </div>
    <div class="col s12">

    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header">Movie Details</div>
        <div class="collapsible-body">
          <span>
            Rating: <%= @trailer['rating']%> <br>
            <% @genre = @trailer['genres']%>
            Genres: <br>
            <%@genre.each do |genre|%>
            * <%= genre['title']%>
            <%end%>
            <br>
            <%@min = @trailer['duration']/60%>
            Duration: <%= @min/60%>
            <br>
          </span>
        </div>
      </li>

      <li>
        <div class="collapsible-header">Overview</div>
        <div class="collapsible-body">
          <span>
              <%= @trailer['overview']%>
          </span>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Directors</div>
        <div class="collapsible-body">
          <span>
            <% @director = @trailer['directors']%>
                <%@director.each do |wrt|%>
                  . <%=wrt['name']%> <br>
                <%end%>
          </span>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Writers</div>
        <div class="collapsible-body">
          <span>
            <% @writer = @trailer['writers']%>
                 <%@writer.each do |wrt|%>
                . <%=wrt['name']%><br>
                <%end%>
          </span>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Cast</div>
        <div class="collapsible-body">
          <span>
            <% @cast = @trailer['cast']%>
                <%@cast.each do |wrt|%>
                  . <%=wrt['name']%> AS: <%= wrt['character_name']%><br>
                <%end%>
          </span>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Trailer</div>
        <div class="collapsible-body">
          <span>
            <%@trailer['trailers']['web'].each do |show|%>
              <%@link2 = show['embed']%>
              <%puts "link", @link %>
            <center>  <iframe src=<%= @link2 %> width="700px" height="370px"></iframe> </center>

            <%end%>
          </span>
        </div>
      </li>
      <li>

        <div class="collapsible-header">Sources</div>
        <div class="collapsible-body">
          <span>
            <p>Free:<br>
            <%@free = @trailer['free_web_sources']%>
            <%if @free != nil %>
              <%@free.each do |free|%>
                . <%= free['display_name']%>
                  <% @link = free['link']%>
                  <a href=<%= @link%>>Watch me!</a> <br>
              <%end%>
            <%end%>
            </p>
          <p>Purchase: <br>
                <%@purchase = @trailer['purchase_web_sources']%>
                <%puts "TRY", @purchase%>
                <%if @purchase != nil %>
                  <%@purchase.each do |purchase|%>
                      <%= purchase['display_name']%>:
                      <% @link = purchase['link']%>
                      <%= link_to "Watch me", @link, :target => "_blank" %> <br>
                  <%end%>
                <%end%></p>
              </span>
            </div>
          </li>
        </ul>
    </div>


  </div>
</div>

Binge-buddy-app/app/views/movies/search_form.html.erb
<div class="searcher container">
  <div class="row">
    <div class="col s12">

        <center><h4 class="homesearch"><i class="large material-icons spacing">search</i>Pick Your Movie: </h4>

        <%= form_tag("/movies/search-results", method: "post") do |f| %>
        <%= label_tag(:search, "Search for a movie:") %>
        <%= text_field_tag(:search) %> <br>
        <%= submit_tag"Submit", class: "btn waves-effect waves-light" %>
        <% end %>
      </center>
    </div>
  </div>
</div>

Binge-buddy-app/app/views/movies/search_results.html.erb
<div class="honeycombs">
  <% if @moviesearch != nil %>
    <%@moviesearch.each do |results|%>
      <% puts "trying again ", results.inspect %>
      <div class="comb">
        <%@title = results['title']%>
        <%@image = results['poster_240x342'].insert(4, 's')%>
        <%@movie_id = results['id']%>

            <img src=<%= @image%>>

          <span>
            <%= @title %><br>
            <% if current_user != nil%>
                <%= link_to "VIEW", {action: :one_result, movie_id: @movie_id, title: @title, user_id: current_user.id }, method: :post, class: "naving" %>
            <%else%>
                <a class=" sign"href="/users/sign_up"> Sign Up</a>
            <%end %>
          </span>
      </div>
    <%end%>
  <%else%>
      <p>No movie found by this title</p>
<%end%>

 </div>




 <script type="text/javascript">
   $(document).ready(function() {
     $('.honeycombs').honeycombs({
       combWidth: 250,
       margin: 10
     });
   });
 </script>
<!--

    <div class="comb">
      <img src="/assets/movie2.jpg"/>
        <span>Image Caption 1</span>
    </div>
    <div class="comb">
      <img src="/assets/movie3.jpg"/>
        <span>Image Caption 1</span>
    </div>
    <div class="comb">
      <img src="/assets/movie4.jpg"/>
        <span>Image Caption 1</span>
    </div>
    <div class="comb">
      <img src="/assets/movie5.jpg"/>
        <span>Image Caption 1</span>
    </div> -->

Binge-buddy-app/app/views/users/show.html.erb
<div class="user-info-div">
  <div class="newprofile container">
    <div class="row">
      <div class="col s6 offset-s3">
        <center>
            <h4>Name:</h4><%= @user.first_name%> <%= @user.last_name%>
            <br><hr>


            <h4>Email:</h4><%=@user.email%>
            <br><hr>

            <h4 id="avatar"><%= image_tag @user.avatar.url%></h4>
            <hr>
            <h4 id="coloredit"><%= link_to "Edit Profile", edit_user_registration_path %></h4>

        </center>
      </div>
    </div>
  </div>
</div>

Binge-buddy-app/app/views/welcome/home.html.erb
<%puts @guidebox.inspect%>

<div class="container">
  <div class="row ">
    <div class="col s12">
      <center><h1 id="header">
        <div id="binge">Binge</div>
        <div id="buddy">B U D D Y</div>
      </h1></center>
    </div>
  </div>

<hr>
  <div class="row size">
    <div class="col s12">
      <div class="col s4 ">
          <div class="hexagon hexagon2">
            <div class="hexagon-in1">
              <div class="hexagon-in2">

              </div>
            </div>
          </div>
          <p class="style">You like movies, but constantly struggle to find where to watch them online?</p>
      </div>

      <div class="col s4">
        <p class="style">Search or Browse through our library!</p>
        <div class="hexagon hexagon3">
          <div class="hexagon-in1">
            <div class="hexagon-in3">

            </div>
          </div>
        </div>
      </div>

      <div class="col s4">
        <div class="hexagon hexagon4">
          <div class="hexagon-in1">
            <div class="hexagon-in4">

            </div>
          </div>
        </div>
        <p class="style"> Make sure to save your favorite movies! Happy Binging!</p>
      </div>
  </div>
</div>
  <hr>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
  <div class="row size">

    <div class="col s12 ">
      <center><h4 class="homesearch"><i class="large material-icons spacing">search</i>Pick Your Movie: </h4>
      <%= form_tag("/movies/search-results", method: "post") do |f| %>
        <%= label_tag(:search, "Search for a movie:") %>
        <%= text_field_tag(:search) %> <br>
      <%= submit_tag "Submit", class: "btn waves-effect waves-light" %>
      <% end %>
    </center>
    </div>
  </div>

<br>
<br>
<br>
<br>
<br>
<br>

  <div class="row">
    <div class="col s12">
      <div class="honeycombs">

        <% @guidebox['results'].each do |movies|%>
          <%@image = movies['poster_240x342'].insert(4, 's')%>
          <% puts "IMAGE",  @image%>
        
          <%@movie_id = movies['id']%>
          <%@title = movies['title']%>
          <div class="comb">
            <img src=<%= @image%>>
            <span><%= @title%><br>
                <% if current_user != nil%>
                    <%= link_to "view this movie", {controller: :movies, action: :one_result, movie_id: @movie_id, title: @title, user_id: current_user.id }, method: :post%>
                <%else%>
                    <!-- <a class=" sign"href="/users/sign_up"> Sign Up</a> -->
                    <%= link_to "view this movie", {controller: :movies, action: :one_result, movie_id: @movie_id, title: @title}, method: :post%>
                <%end %>
            </span>
          </div>
        <%end%>
      </div>

    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.honeycombs').honeycombs({
        combWidth: 250,
        margin: 10
      });
    });
  </script>
</div> <!-- end of container -->